#!/bin/bash

DATABASE_PASSWORD=${DATABASE_PASSWORD:-''}
DATABASE_HOST=${DATABASE_HOST:-''}
DATABASE_USER=${DATABASE_USER:-''}
DATABASE_K8S_KIND=${DATABASE_K8S_KIND:-''}

K8S_CONFIG=${K8S_CONFIG:-'it'}

NAMESPACE=${NAMESPACE:-'project'}

MISSING_RANGE_SUFFIX_FILLING=${MISSING_RANGE_SUFFIX_FILLING:-0}
MISSING_RANGE_SUFFIX_LENGTH=${MISSING_RANGE_SUFFIX_LENGTH:-3}
MISSING_RANGE_SUFFIX_START=${MISSING_RANGE_SUFFIX_START:-0}
MISSING_RANGE_SUFFIX_END=${MISSING_RANGE_SUFFIX_END:-0}
MISSING_RANGE_PREFIX=${MISSING_RANGE_PREFIX:-'email-'}